# Generated by Django 3.2.25 on 2024-09-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuserrelation',
            name='side',
            field=models.CharField(default='left', max_length=5),
        ),
    ]
