# Generated by Django 3.2.25 on 2024-09-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_game_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date_time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
