# Generated by Django 3.2.25 on 2024-09-23 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_game_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='state',
        ),
    ]
