version: '3.8'

services:
  db:
    build:
      context: ./srcs/PostgreSQL
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_started
    environment:
      ADMINER__SERVER: db
    networks:
      - network

  redis:
    container_name: redis
    build: ./srcs/redis
    restart: always
    env_file:
      - .env
    networks:
      - network

  web:
    build:
      context: ./srcs/django
    container_name: django_web
#    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./srcs/django:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - network

volumes:
  postgres_data:
  # driver: local # Define the driver and options under the volume name
  #   driver_opts:
  #     type: none
  #     device: ~/data/db_data
  #     o: bind

networks:
  network:
    driver: bridge