# srcs/PostgreSQL/Dockerfile
FROM postgres:13

# Add environment variables for PostgreSQL
ENV POSTGRES_DB=db
ENV POSTGRES_USER=edupless
ENV POSTGRES_PASSWORD=7142128

# Expose the PostgreSQL port
EXPOSE 5432
